[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[template.environment]
  JWT_SECRET = "KJnkgjsfdkh898346374736jkgdfgdjk"
